Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\connection_cext.py", line 200, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'localhost' (10061)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pc\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Pc\Music\New folder\login_support.py", line 33, in login
    conn=mysql.connect(host="localhost",user="root",passwd="",database="mysqldb")
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\__init__.py", line 176, in connect
    return CMySQLConnection(*args, **kwargs)
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\connection_cext.py", line 80, in __init__
    self.connect(**kwargs)
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\abstracts.py", line 781, in connect
    self._open_connection()
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\connection_cext.py", line 203, in _open_connection
    sqlstate=exc.sqlstate)
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost' (10061)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Pc\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Pc\Music\New folder\login_support.py", line 37, in login
    c.execute(sqlstat,task)
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\cursor_cext.py", line 261, in execute
    "Not all parameters were used in the SQL statement")
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Pc\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Pc\Music\New folder\login_support.py", line 37, in login
    c.execute(sqlstat,task)
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\cursor_cext.py", line 261, in execute
    "Not all parameters were used in the SQL statement")
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Pc\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Pc\Music\New folder\login_support.py", line 37, in login
    c.execute(sqlstat,task)
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\cursor_cext.py", line 261, in execute
    "Not all parameters were used in the SQL statement")
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Pc\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Pc\Music\New folder\login_support.py", line 37, in login
    c.execute(sqlstat,task)
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\cursor_cext.py", line 261, in execute
    "Not all parameters were used in the SQL statement")
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Pc\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Pc\Music\New folder\login_support.py", line 37, in login
    c.execute(sqlstat,task)
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\cursor_cext.py", line 261, in execute
    "Not all parameters were used in the SQL statement")
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Pc\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Pc\Music\New folder\login_support.py", line 37, in login
    c.execute(sqlstat,task)
  File "C:\Users\Pc\Anaconda3\lib\site-packages\mysql\connector\cursor_cext.py", line 261, in execute
    "Not all parameters were used in the SQL statement")
mysql.connector.errors.ProgrammingError: Not all parameters were used in the SQL statement
